const assert=require('node:assert/strict'),E=require('./dist/engine.js'),D=require('./dist/data.js');
const modern=p=>D.accounts({cash:0,other:0,debtOther:0,pools:[{name:'QA',cash:20,other:50,type:'質押',...p}]});
const pledge=modern({pledgeValue:100,pledgeDebt:50,marginValue:0,marginDebt:0}),margin=modern({pledgeValue:0,pledgeDebt:0,marginValue:100,marginDebt:50});
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
close(E.capacity(pledge).current,.17);close(E.capacity(pledge).stocks,1-83/150);close(E.capacity(pledge).cash,.668);
close(E.capacity(margin).current,.35);close(E.capacity(margin).stocks,1-65/150);close(E.capacity(margin).cash,.74);
assert.ok(E.capacity(margin).cash>E.capacity(margin).stocks);
const mixed=modern({pledgeValue:166,pledgeDebt:100,marginValue:130,marginDebt:100});mixed.pools[0].other=30;D.sync(mixed);
close(E.capacity(mixed).stocks,30/326);close(E.capacity(mixed).cash,56/290);
const staged={...mixed,usePledge:true,pools:mixed.pools.map(p=>({...p,pledge:p.other}))};
close(E.calculate(staged,.2,true).repay,20+2/1.3);close(E.calculate(staged,.2,true).cashGap,2/1.3);
close(E.calculate(staged,.2).stock,326*.8);close(E.calculate(staged,.2).equity,326*.8+20-200);
const split=modern({pledgeValue:100,pledgeDebt:100,marginValue:1000,marginDebt:100});split.pools[0].other=0;D.sync(split);assert.equal(E.capacity(split).current,0);assert.ok(E.calculate(split).breached>0);
const isolated=D.accounts({cash:0,other:0,debtOther:0,pools:[{name:'A',type:'融資',value:100,debt:50,cash:0,other:0},{name:'B',type:'質押',value:0,debt:0,cash:0,other:1000}]});close(E.capacity(isolated).stocks,.35);isolated.pools[1].cash=10;D.sync(isolated);close(E.capacity(isolated).cash,.48);
close(E.calculate({...margin,usePledge:true,pools:margin.pools.map(p=>({...p,pledge:p.other}))}).pools[0].components[0].ratio,300);
console.log('Passed: pledge166/margin130, split contracts, optimal same-broker stock allocation, cash pooling, no cross-broker stock or asset double counting.');

const below166=modern({pledgeValue:150,pledgeDebt:100,marginValue:0,marginDebt:0});below166.pools[0].cash=0;below166.pools[0].other=0;D.sync(below166);
assert.equal(E.capacity(below166).current,0);assert.equal(E.calculate(below166).breached,1);assert.equal(E.capacity(below166).cash,0);
close(E.calculate(staged,.2).repay,20+2/1.3);
console.log('Passed: every displayed stage uses pledge166/margin130; pledged150 yields zero conservative buffer.');
