const assert=require('node:assert/strict');
global.RiskEngine=require('./dist/engine.js');
const {normalize}=require('./dist/data.js');
const raw={version:2,date:'2026-10-01',mode:'使用者輸入',drop:30,members:[{name:'媽媽',data:{cash:10,other:50,debtOther:0,pools:[{name:'券商A',type:'質押',value:100,debt:50,trigger:130,target:166,collateral:50,fixed:100,secret:'do not copy'}]}}]};
const result=normalize(raw);assert.equal(result.drop,30);assert.equal(result.members[0].data.pools[0].value,100);assert.equal('fixed' in result.members[0].data.pools[0],false);assert.equal('secret' in result.members[0].data.pools[0],false);
result.members[0].data.cash=99;assert.equal(raw.members[0].data.cash,10);
assert.throws(()=>normalize({...raw,members:[] }));
assert.throws(()=>normalize({...raw,members:[{name:'A',data:{...raw.members[0].data,cash:NaN}}]}));
assert.throws(()=>normalize({...raw,members:[{name:'A',data:{...raw.members[0].data,pools:[{...raw.members[0].data.pools[0],target:129}]}}]}));
assert.equal(normalize({...raw,drop:99}).drop,20);
assert.equal(normalize(raw.members[0].data).members.length,1);
assert.throws(()=>normalize({version:2,members:Array.from({length:31},()=>raw.members[0])}));
console.log('Passed: cloud snapshot validation, legacy fields removed, independent copies, corrupt data rejected.');
