const assert=require('node:assert/strict');require('./dist/engine.js');const S=require('./dist/summary.js');
const m=[{name:'QA',data:{cash:10,other:100,debtOther:0,usePledge:false,pools:[{name:'合計',type:'質押',value:200,debt:150,pledge:100}]}}];
let text=S.generate(m,.3,'2026-10-01');assert.match(text,/股票下跌 30% 後/);assert.match(text,/情境現金不足/);assert.match(text,/借款／總資產 48.39%/);assert.match(text,/1.88 倍/);assert.match(text,/未套用追加股票/);assert.match(text,/無法判斷個別券商/);
m[0].data.usePledge=true;text=S.generate(m,.3);assert.match(text,/情境下整體擔保足夠/);assert.match(text,/已套用全部現股投入/);
m[0].data.pools[0].debt=400;text=S.generate(m,.56);assert.match(text,/淨資產非正，無法計算/);assert.match(text,/下跌 56%/);assert.doesNotMatch(text,/Infinity|NaN/);
console.log('Passed: summary risk indicators, exact selected decline, cash gaps, stock support switch and non-positive equity.');
const D=require('./dist/data.js');
const scoped=D.accounts({cash:0,other:0,debtOther:0,pools:[{name:'無借款',cash:0,other:900,value:0,debt:0},{name:'券商 A',cash:0,other:10,value:150,debt:100},{name:'券商 B',cash:0,other:500,value:300,debt:100}]});
const summary=S.generate([{name:'測試',data:scoped}],.3);
assert.match(summary,/合計 1,410 萬，不跨券商調用/);
assert.match(summary,/券商 A（該券商追加現股 10 萬） 最早碰到追繳門檻/);
assert.doesNotMatch(summary,/券商 A（該券商追加現股 900/);
console.log('Passed: total unpledged stock distinguished from first-call broker own stock, including debt-free accounts.');
